server:
  port : 6001
  
spring:
  cloud:
    gateway:
      routes:
      - id: header_route1
        uri: http://localhost:8082/cbs/lookups
        predicates:
        - Path=/cbs/**
        - Header=BankCode, SRCB02
      - id: header_route2
        uri: http://10.100.9.105
        predicates:
        - Path=/cbs/create/account
        - Header=BankCode, SRCB01
        filters:
        - RewritePath=/cbs(?<segment>/?.*), /EBS_API/AccountOpening$\{segment}
      - id: header_route3
        uri: http://10.100.9.105
        predicates:
        - Path=/cbs/**
        - Header=BankCode, SRCB01
        filters:
        - RewritePath=/cbs(?<segment>/?.*), /EBS_API/AccountOpening/request$\{segment}
      
  security: 
    user: 
      name: sil@123
      password: Sil@123
      
logging:
  file:
    name: CloudLog.log
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
    
  